/// Model representing Emergency Shelter Battery & Solar Micro-Grid Power Budget
class DevicePowerConsumption {
  final String deviceName;
  final double wattage;
  final double dailyUsageHours;
  final bool isLifesavingCritical;

  const DevicePowerConsumption({
    required this.deviceName,
    required this.wattage,
    required this.dailyUsageHours,
    required this.isLifesavingCritical,
  });

  double get dailyWattHours => wattage * dailyUsageHours;
}

class EmergencyPowerBudget {
  final double batteryBankCapacityWattHours;
  final double currentBatteryChargePercent;
  final double solarPanelPeakWatts;
  final double expectedDailyPeakSunHours;
  final List<DevicePowerConsumption> connectedAppliances;

  const EmergencyPowerBudget({
    required this.batteryBankCapacityWattHours,
    required this.currentBatteryChargePercent,
    required this.solarPanelPeakWatts,
    required this.expectedDailyPeakSunHours,
    required this.connectedAppliances,
  });

  /// Available usable energy in battery bank
  double get usableBatteryWattHours => (batteryBankCapacityWattHours * (currentBatteryChargePercent / 100.0)) * 0.85; // 85% depth-of-discharge safe

  /// Daily energy generated by emergency solar PV array
  double get dailySolarGenerationWattHours => solarPanelPeakWatts * expectedDailyPeakSunHours * 0.75; // 75% system efficiency

  /// Total daily energy demand across all connected equipment
  double get totalDailyDemandWattHours {
    return connectedAppliances.fold(0.0, (sum, dev) => sum + dev.dailyWattHours);
  }

  /// Estimated autonomy time (days) in total blackout (0 solar generation)
  double get blackoutAutonomyDays {
    if (totalDailyDemandWattHours == 0) return 99.0;
    return usableBatteryWattHours / totalDailyDemandWattHours;
  }

  /// Returns true if solar recharge is sufficient to achieve sustainable daily power balance
  bool get isSolarNetPositive => dailySolarGenerationWattHours >= totalDailyDemandWattHours;
}
